appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: COrvKP3G6kgqpzbcm6WyIKAd4BUA5Og9Sb08vjCoKiQPJiyP8rf8/joB6OgBd/P4KYbaToyME4vcexpEMFj4S9eZJI4/MiirpJUkK+ZFV5JJdHTHJtZ4B1Mfb+Xw5I8nC9gTtnNfg7RRZ/+hjUYrmAUPO7u6jFEigSiGjO9lJwSeFe338iot7URgz0L069h0Po4lEEux+XZnTQxHZLyD52M15RKzMdMhm+LuVf/blgiyMluBuSmX33DqxRhvi4ffRKkIEgVsMfhFVn4n9w4KFJCeFrq82BUA+Kw5mHyReO/iaYGm1mNQsSHsq4Ha6UGxtblQo0WIzrw+d/yRAjfzD2KgI/vo9iSaJbiyRdwA283FyUsjZg8dhe24lP1Wbj0HPyfYdgK61cYKCjC3ny1DskJpdeFIBSmfPYK1upL0HriCfokT/+NAQ9/SRhJspetaTragIdCLe4pmxHrE2uJ4sUrR5FJZPkl6CT5UQDsGufZV7V30snILLEKU1n6CVhrrSx1kVHJslGt/NpjtBd4znnIG9qgZ9nqFlGaQgFUCzJDx/YoxpIfu3QIF2BRMFjs/H+PtwzpIsoU+BUy/ogoubaA5c2TRgYTarnB8bWbf8Kc8JW+kfnBFuv6e0gFNmxfhUXt/YSBvbMmSfJEx4evL0gAxXwH1Pia+wgYieepc1lU=
